apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pod-gateway
  namespace: vpn-gateway
spec:
  interval: 15m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: vpn-gateway
        namespace: flux-system
  maxHistory: 2
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
  - kind: ConfigMap
    name: pod-gateway-helm-chart-value-overrides
    valuesKey: values.yaml